config/routes.rb
Rails.application.routes.draw do

  get 'about/about', as: 'about'

  get 'mboard/index'

  get 'mboard/new'

  get 'guestbooks/index'

  get 'admin/comments/index'

  devise_for :users, controllers: {

    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  mount Ckeditor::Engine => '/ckeditor'
  resources :posts do 
    resources :comments do
      resources :replies
    end
  end
  resources :category

  resources :games do 
    resources :comments
  end

  resources :mboards do
    resources :comments
  end

  namespace :admin do
    resources :posts do
      collection do
        delete 'multi_del'
      end
    end
    resources :comments do
      collection do
        delete 'multi_del'
      end
    end
    resources :replies do
      collection do
        delete 'multi_del'
      end
    end
    resources :games do
      collection do
        delete 'multi_del'
      end
    end
    resources :mboards do
      collection do
        delete 'multi_del'
      end
    end
  end

  get '/games/:id/new_review', to: 'games#add_review', as: 'new_review'
  
  get 'comments/:id/edit_review', to: "comments#edit_review", as: "edit_review"

  root 'posts#index'

  get '/category_post', to: 'posts#category_post'

  post '/mboards/add_comment', to: 'mboards#add_comment'

end

app/models/admin/mboard.rb
class Admin::Mboard < Mboard
end

app/models/mboard.rb
class Mboard < ApplicationRecord
  validates :post, presence: true
  has_many :comments, as: :commentable, dependent: :destroy
  # accepts_nested_attributes_for :comments
end

app/controllers/admin/mboards_controller.rb
class Admin::MboardsController < ApplicationController
  layout 'admin'
  before_action :set_admin_mboard, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :auth_user

  # GET /admin/mboards
  # GET /admin/mboards.json
  def index
    @admin_mboards = Admin::Mboard.all.page(params[:page])
  end

  # GET /admin/mboards/1
  # GET /admin/mboards/1.json
  def show
  end

  # GET /admin/mboards/new
  def new
    @admin_mboard = Admin::Mboard.new
  end

  # GET /admin/mboards/1/edit
  def edit
  end

  # POST /admin/mboards
  # POST /admin/mboards.json
  def create
    @admin_mboard = Admin::Mboard.new(admin_mboard_params)

    respond_to do |format|
      if @admin_mboard.save
        format.html { redirect_to admin_mboards_path, notice: 'Mboard was successfully created.' }
        format.json { render :show, status: :created, location: @admin_mboard }
      else
        format.html { render :new }
        format.json { render json: @admin_mboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/mboards/1
  # PATCH/PUT /admin/mboards/1.json
  def update
    respond_to do |format|
      if @admin_mboard.update(admin_mboard_params)
        format.html { redirect_to @admin_mboard, notice: 'Mboard was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_mboard }
      else
        format.html { render :edit }
        format.json { render json: @admin_mboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/mboards/1
  # DELETE /admin/mboards/1.json
  def destroy
    @admin_mboard.destroy
    respond_to do |format|
      format.html { redirect_to admin_mboards_url, notice: 'Mboard was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def multi_del
    Mboard.destroy_all(id: params[:del_mboards])
    redirect_back(fallback_location: root_path, notice: '刪除成功')

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_mboard
      @admin_mboard = Admin::Mboard.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_mboard_params
      params.require(:admin_mboard).permit(:name, :post)
    end
end

app/controllers/mboards_controller.rb
class MboardsController < ApplicationController

  before_action :set_post, only: [:show, :destroy, :update]
  before_action :authenticate_user!, except: [:index, :show]
  
  def index
    @posts = Mboard.includes(:comments).order("created_at desc")
    @comment = Comment.new
  end

  def new
    @post = Mboard.new
  end

  def create
    @post = Mboard.new(post_params)
    if @post.save
      redirect_to mboards_path, notice: '留言新增成功'
    else
      render action: 'new', notice: '內容不得為空'
    end
  end

  def show
  end

  def add_comment
    @post = Mboard.find(params[:comment][:post_id])
    @comment = @post.comments.build(comment_params)
    if @comment.save
      redirect_to mboards_path, notice: "回覆成功"
    else
      render :back
    end
  end

  def update
    @post.update(post_params)
    respond_to do |format|
      if @post.save
        format.html { redirect_to mboards_path, notice: "編輯成功"}
      else
        format.html { render :back}
      end
    end
  end

  def destroy
    @post.destroy
    redirect_to mboards_path, notice: "刪除成功"
  end


  private

  def post_params
    params.require(:mboard).permit(:name, :post)
  end

  def comment_params
    params.require(:comment).permit(:name, :comment, :user_id)
  end

  def set_post
    @post = Mboard.find(params[:id])
  end
end

app/helpers/admin/mboards_helper.rb
module Admin::MboardsHelper
end

app/helpers/mboard_helper.rb
module MboardHelper
end

app/views/admin/mboards/_form.html.erb
<%= form_for(admin_mboard) do |f| %>
  <%= f.label :name, current_user.name %>
  <%= f.hidden_field :name, value: current_user.name %>
  <%= f.text_area :post, "data-provide": "markdown", required: true %><br>
  <%= f.submit "送出", class: 'btn btn-primary'%>
<% end %>

app/views/admin/mboards/edit.html.erb
<h1>Editing Admin Mboard</h1>

<%= render 'form', admin_mboard: @admin_mboard %>

<%= link_to 'Show', @admin_mboard %> |
<%= link_to 'Back', admin_mboards_path %>

app/views/admin/mboards/index.html.erb
<h1>留言板管理</h1>

<%= form_tag multi_del_admin_mboards_path, method: :delete do %>
  <div class="table-responsive"> 
    <table class="table">
      <thead>
        <th>選取</th>
        <th>日期</th>
        <th>留言者</th>
        <th>內容</th>
      </thead>
      <tbody> 
        <% @admin_mboards.each do |mboard| %>
          <tr>
            <td><%= check_box_tag "del_mboards[]", mboard.id %></td>
            <td><%= mboard.created_at.strftime("%Y/%m/%d") %></td>
            <td><%= mboard.name %></td>
            <td><%= sanitize(markdown(mboard.post)) %></td>
            <td><%= link_to "刪除", admin_mboard_path(mboard), method: :delete, class: 'btn btn-danger btn-xs' %></td>
          <tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <%= submit_tag "刪除所選文章", data: { confirm: '確定刪除?' }, class: 'btn btn-danger' %>
<% end %>
<%= paginate @admin_mboards %>

<%= link_to '新增留言', new_admin_mboard_path %>

app/views/admin/mboards/new.html.erb
<h1>新增留言</h1>

<%= render 'form', admin_mboard: @admin_mboard %>

<%= link_to 'Back', admin_mboards_path %>

app/views/admin/mboards/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_admin_mboard_path(@admin_mboard) %> |
<%= link_to 'Back', admin_mboards_path %>