config/routes.rb
Rails.application.routes.draw do

  get 'about/about', as: 'about'

  get 'mboard/index'

  get 'mboard/new'

  get 'guestbooks/index'

  get 'admin/comments/index'

  devise_for :users, controllers: {

    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  mount Ckeditor::Engine => '/ckeditor'
  resources :posts do 
    resources :comments do
      resources :replies
    end
  end
  resources :category

  resources :games do 
    resources :comments
  end

  resources :mboards do
    resources :comments
  end

  namespace :admin do
    resources :posts do
      collection do
        delete 'multi_del'
      end
    end
    resources :comments do
      collection do
        delete 'multi_del'
      end
    end
    resources :replies do
      collection do
        delete 'multi_del'
      end
    end
    resources :games do
      collection do
        delete 'multi_del'
      end
    end
    resources :mboards do
      collection do
        delete 'multi_del'
      end
    end
  end

  get '/games/:id/new_review', to: 'games#add_review', as: 'new_review'
  
  get 'comments/:id/edit_review', to: "comments#edit_review", as: "edit_review"

  root 'posts#index'

  get '/category_post', to: 'posts#category_post'

  post '/mboards/add_comment', to: 'mboards#add_comment'

end

app/models/admin/comment.rb
class Admin::Comment < Comment
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
  has_many :replies, dependent: :destroy
  # validates :name, presence: true
  # validates :comment, presence: true
  belongs_to :user
  validates :comment, presence: true
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
  layout "admin"
  before_action :set_admin_comment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :auth_user

  # GET /admin/comments
  # GET /admin/comments.json
  def index
    if params[:type] == "game"
      @admin_comments = Admin::Comment.where(commentable_type: "Game")
    elsif params[:type] == "mboard"
      @admin_comments = Admin::Comment.where(commentable_type: "Mboard")
    else
      @admin_comments = Admin::Comment.where(commentable_type: "Post")
    end
  end

  # GET /admin/comments/1
  # GET /admin/comments/1.json
  def show
  end

  # GET /admin/comments/new
  def new
    @admin_comment = Admin::Comment.new
  end

  # GET /admin/comments/1/edit
  def edit
  end

  # POST /admin/comments
  # POST /admin/comments.json
  def create
    @admin_comment = Admin::Comment.new(admin_comment_params)

    respond_to do |format|
      if @admin_comment.save
        format.html { redirect_to @admin_comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @admin_comment }
      else
        format.html { render :new }
        format.json { render json: @admin_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/comments/1
  # PATCH/PUT /admin/comments/1.json
  def update
    respond_to do |format|
      if @admin_comment.update(admin_comment_params)
        format.html { redirect_to @admin_comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_comment }
      else
        format.html { render :edit }
        format.json { render json: @admin_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/comments/1
  # DELETE /admin/comments/1.json
  def destroy
    @admin_comment.destroy
    respond_to do |format|
      format.html { redirect_back(fallback_location: root_path, notice: '刪除成功') }
      format.json { head :no_content }
    end
  end

  def multi_del
    Comment.destroy_all(id: params[:del_comments])
    redirect_back(fallback_location: root_path, notice: '刪除成功') 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_comment
      @admin_comment = Admin::Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_comment_params
      params.fetch(:admin_comment, {})
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_comment, only: [:edit, :update, :destroy, :edit_review]

  def create
    if params[:post_id]
      @post = Post.find(params[:post_id])
      @comment = @post.comments.build(comment_params)
      if @comment.save
        redirect_to post_path(@post), notice: "回覆成功"
      else
        redirect_to post_path(@post), alert: "回復失敗"
      end
    else
      @game = Game.find(params[:game_id])
      @comment = @game.comments.build(comment_params)
      if @comment.save
        redirect_to game_path(@game), notice: "回覆成功" 
      else
        redirect_to game_path(@game), alert: "回復失敗" 
      end
    end
  end

  def edit
  end

  def edit_review
    respond_to do |format|
      format.html
      format.js
    end
  end

  def update
    if @comment.commentable.class.name == "Game"
      if @comment.update(comment_params)
        redirect_to game_path(@comment.commentable), notice: "修改成功"
      else
        redirect_to game_path(@comment.commentable), notice: "修改失敗"
      end
    else
      respond_to do |format|
        if @comment.update(comment_params)
          format.html { redirect_to post_path(@comment.commentable), notice: "修改成功" }
          format.json { respond_with_bip(@comment) }
        end
      end
    end
  end

  def destroy
    if @comment.destroy && !!params[:post_id]
      redirect_to post_path(@comment.commentable), notice: '留言刪除成功'
    elsif @comment.destroy && !!params[:mboard_id]
      respond_to do |format|
        format.html { redirect_to mboards_path, notice: '留言刪d除成功' }
        format.js 
      end
    else @comment.destroy && !!params[:game_id]
      redirect_to game_path(@comment.commentable), notice: '留言刪除成功'
    end
  end

  private
  
  def comment_params
    params.require(:comment).permit(:name, :comment, :rating)
  end

  def set_comment
    @comment = Comment.includes(:replies).find(params[:id]) 
  end

end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
  def link_to_post(comment)
    if comment.commentable_type == "Mboard"
      link_to truncate(raw(markdown(Mboard.find(comment.commentable_id).post)), length: 30, escape: false), mboards_path, target: '_blank'
    elsif comment.commentable_type == "Game"
      link_to Game.find(comment.commentable_id).title, game_path(comment.commentable_id), target: '_blank'
    else
      link_to Post.find(comment.commentable_id).title, post_path(comment.commentable_id), target: '_blank'

    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/admin/comments/_form.html.erb
<%= form_tag multi_del_admin_comments_path, method: :delete do %>
  <div class="table-responsive"> 
    <table class="table">
      <thead>
        <tr>
          <th>選取</th>
          <th>留言人</th>
          <th>內容</th>
          <th>文章標題</th>
        </tr>
      </thead>

      <tbody>
        <% @admin_comments.each do |admin_comment| %>
          <tr>
            <td><%= check_box_tag "del_comments[]", admin_comment.id %></td>
            <td><%= admin_comment.name %></td>
            <td><%= admin_comment.comment %></td>
            <td><%= link_to_post(admin_comment)  %></td>
            <td><%= link_to '刪除', admin_comment_path(admin_comment), method: :delete, data: { confirm: 'Are you sure?' },class: 'btn btn-danger btn-xs' %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <%= submit_tag "刪除所選留言", data: {contirm: '確定刪除?'}, class: 'btn btn-danger' %>
<% end %>

app/views/admin/comments/edit.html.erb
<h1>Editing Admin Comment</h1>

<%= render 'form', admin_comment: @admin_comment %>

<%= link_to 'Show', @admin_comment %> |
<%= link_to 'Back', admin_comments_path %>

app/views/admin/comments/index.html.erb
<h1>Blog留言管理</h1>
<div class="dropdown">
  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
    選擇管理區塊
    <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
    <li role="presentation"><%= link_to 'Blog留言管理', admin_comments_path(type: "blog"), role: 'menuitem', tabindex: '-1' %></li>
    <li role="presentation"><%= link_to '遊戲review留言管理', admin_comments_path(type: "game"), role: 'menuitem', tabindex: '-1' %></li>
     <li role="presentation"><%= link_to '留言板留言', admin_comments_path(type: "mboard"), role: 'menuitem', tabindex: '-1' %></li>
    <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Separated link</a></li>
  </ul>
</div>
<br>

<%= render partial: 'form' %>

app/views/admin/comments/new.html.erb
<h1>New Admin Comment</h1>

<%= render 'form', admin_comment: @admin_comment %>

<%= link_to 'Back', admin_comments_path %>

app/views/admin/comments/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_admin_comment_path(@admin_comment) %> |
<%= link_to 'Back', admin_comments_path %>