config/routes.rb
Rails.application.routes.draw do

  get 'about/about', as: 'about'

  get 'mboard/index'

  get 'mboard/new'

  get 'guestbooks/index'

  get 'admin/comments/index'

  devise_for :users, controllers: {

    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  mount Ckeditor::Engine => '/ckeditor'
  resources :posts do 
    resources :comments do
      resources :replies
    end
  end
  resources :category

  resources :games do 
    resources :comments
  end

  resources :mboards do
    resources :comments
  end

  namespace :admin do
    resources :posts do
      collection do
        delete 'multi_del'
      end
    end
    resources :comments do
      collection do
        delete 'multi_del'
      end
    end
    resources :replies do
      collection do
        delete 'multi_del'
      end
    end
    resources :games do
      collection do
        delete 'multi_del'
      end
    end
    resources :mboards do
      collection do
        delete 'multi_del'
      end
    end
  end

  get '/games/:id/new_review', to: 'games#add_review', as: 'new_review'
  
  get 'comments/:id/edit_review', to: "comments#edit_review", as: "edit_review"

  root 'posts#index'

  get '/category_post', to: 'posts#category_post'

  post '/mboards/add_comment', to: 'mboards#add_comment'

end

app/models/admin/game.rb
class Admin::Game < Game
end

app/models/game.rb
class Game < ApplicationRecord
  mount_uploader :image, ImageUploader
  has_many :comments, as: :commentable, dependent: :destroy
end

app/controllers/admin/games_controller.rb
class Admin::GamesController < ApplicationController
  layout 'admin'
  before_action :set_admin_game, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :auth_user

  # GET /admin/games
  # GET /admin/games.json
  def index
    @admin_games = Admin::Game.all.page(params[:page])
  end

  # GET /admin/games/1
  # GET /admin/games/1.json
  def show
  end

  # GET /admin/games/new
  def new
    @admin_game = Admin::Game.new
  end

  # GET /admin/games/1/edit
  def edit
  end

  # POST /admin/games
  # POST /admin/games.json
  def create
    @admin_game = Admin::Game.new(admin_game_params)

    respond_to do |format|
      if @admin_game.save
        format.html { redirect_to @admin_game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @admin_game }
      else
        format.html { render :new }
        format.json { render json: @admin_game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/games/1
  # PATCH/PUT /admin/games/1.json
  def update
    respond_to do |format|
      if @admin_game.update(admin_game_params)
        format.html { redirect_to @admin_game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_game }
      else
        format.html { render :edit }
        format.json { render json: @admin_game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/games/1
  # DELETE /admin/games/1.json
  def destroy
    @admin_game.destroy
    respond_to do |format|
      format.html { redirect_to admin_games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def multi_del
    Game.destroy_all(id: params[:del_games])
    redirect_back(fallback_location: root_path, notice: '刪除成功')
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_game
      @admin_game = Admin::Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_game_params
      params.require(:admin_game).permit(:title,:os,:rating,:review,:company, :image)
    end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :find_game, only:[:show,:edit,:update,:destroy, :add_review]
  before_action :authenticate_user!, except: [:index, :show, :add_review]
  before_action :auth_user, except: [:index, :show]
  before_action :never_review?, only: [:add_review]

  def index
    @games = Game.all
  end

  def new
    @game = Game.new
  end

  def create
    @game = Game.new(game_params)
    if @game.save
      redirect_to game_path(@game), notice: "新增成功"
    else
      render action: "new"
    end
  end

  def edit
  end

  def update
    if @game.update(game_params)
      redirect_to game_path(@game), notice: "修改成功"
    else
      render action: "edit"
    end

  end

  def destroy
    if @game.destroy
      redirect_to games_path, notice: "刪除成功"
    end
  end

  def show
    if user_signed_in?
      @my_review = @game.comments.find_by(name: current_user.name)
    end
  end

  def add_review
    @review = @game.comments.build
    respond_to do |format|
      format.html
      format.js
    end
  end



  private

  def game_params
    params.require(:game).permit(:title,:os,:rating,:review,:company, :image)
  end

  def find_game
    @game = Game.includes(:comments).find(params[:id])
  end

  def never_review?
    if !!Game.find(params[:id]).comments.find_by(name: current_user.name)
      render nothing: true, status: 401
    end
  end


end

app/helpers/admin/games_helper.rb
module Admin::GamesHelper
end

app/helpers/games_helper.rb
module GamesHelper
  def has_user_review?(game)
    !!game.comments.find_by(name: current_user.name)
  end
end

app/views/admin/games/_form.html.erb
<%= form_for @admin_game do |f| %>
  <div class="form-group">
    <%= f.label :title, "遊戲名稱" %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <div class="form-group">
    <%= f.label :company, "遊戲公司" %>
    <%= f.text_field :company, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :os, "平台" %>
    <%= f.text_field :os, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :rating, "評分" %>
    <div id="star-rating" data-score=<%= @admin_game.rating %>></div>
  </div>

  <div class="form-group">
    <%= f.label :review, "介紹" %>
    <%= f.cktext_area :review, class: "form-control" %>
  </div>

  <%= f.submit "送出", class: "btn btn-primary" %>
<% end %>

app/views/admin/games/_games_list.html.erb
<%= form_tag multi_del_admin_games_path, method: :delete do %>
  <div class="table-responsive"> 
    <table class="table">
      <thead>
        <th>選取</th>
        <th>日期</th>
        <th>標題</th>
        <th>分類</th>
      </thead>
      <tbody> 
        <% @admin_games.each do |game| %>
          <tr>
            <td><%= check_box_tag "del_games[]", game.id %></td>
            <td><%= game.created_at.strftime("%Y/%m/%d") %></td>
            <td><%= link_to game.title, game_path(game), target: '_blank' %></td>
            <td><%= link_to "編輯", edit_game_path(game), target: '_blank', class: 'btn btn-info btn-xs' %></td>
            <td><%= link_to "刪除", admin_game_path(game), method: :delete, class: 'btn btn-danger btn-xs' %></td>
          <tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <%= submit_tag "刪除所選文章", data: { confirm: '確定刪除?' }, class: 'btn btn-danger' %>
<% end %>
<%= paginate @admin_games %>

app/views/admin/games/edit.html.erb
<h1>編輯遊戲review</h1>

<%= render 'form', admin_game: @admin_game %>

<%= link_to 'Show', @admin_game %> |
<%= link_to 'Back', admin_games_path %>

app/views/admin/games/index.html.erb
<h1>Game List</h1>
<% if @admin_games.blank? %>
  <p>沒有相關文章</p>
<% else %>
  <%= render partial: 'games_list', object: @admin_games %>
<% end %>

app/views/admin/games/new.html.erb
<h1>New Admin Game</h1>

<%= render 'form', admin_game: @admin_game %>

<%= link_to 'Back', admin_games_path %>

app/views/admin/games/show.html.erb
<h1>遊戲介紹</h1>
  <%= image_tag @admin_game.image.medium.url unless @admin_game.image.blank? %><br>
<p>標題: <%= @admin_game.title %></p>
<p>製作公司: <%= @admin_game.company %></p>
<p>平台: <%= @admin_game.os %></p>
<p>評分: <div class="star-rating" data-score=<%= @admin_game.rating %> ></div></p>
<p>介紹: </p>
<span><%= raw @admin_game.review %></span>

<% if is_admin?(current_user) %>
  <%= link_to "修改", edit_game_path(@admin_game) %>
  <%= link_to "刪除", game_path(@admin_game), method: :delete, data: {confirm: "確定刪除?"} %>
<% end %>
<% if user_signed_in? && @my_review%>
  <hr>
  <p>My Review</p>
  <div class="well my-game-review media"> 
    <div class="media-left">
      <%= image_tag user_image(current_user)%>
    </div>
    <div class="media-body">
      <%= @my_review.comment %>
      <div class="game-rating" data-score=<%= @my_review.rating %> ></div></p>
      <p><%= link_to "刪除", game_comment_path(@admin_game, @my_review), method: :delete %>|<%= link_to "編輯", edit_review_path(@my_review), {remote: true, 'data-toggle': "modal", 'data-target': "#modal-window"} %><p>
    </div>
  </div>
  <hr>
<% end %>

<p>使用者review<p>
<div id="modal-window" class="modal" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div>

<% if user_signed_in? && !has_user_review?(@admin_game)%>
  <%= link_to "新增review", new_review_path(@admin_game), {remote: true, 'data-toggle': "modal", 'data-target': '#modal-window'}%>
<% end %>

<div class="well game-review">
  <% @admin_game.comments.each do |comment| %>
    <div class="media">
      <div class="media-left">
      <% commented_user = User.find_by(name: comment.name) %>
        <%= image_tag user_image(commented_user) %>
      </div>
      <div class="media-body">
        <p><%= commented_user.name %></p>
        <span><%= comment.comment %></span>
        <div class="game-rating" data-score=<%= comment.rating %> ></div></p>
        <% if is_admin?(current_user)  %>
          <p><%= link_to "刪除", game_comment_path(@admin_game, comment), method: :delete, data: {confirm: "確定刪除?" } %></p>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<%= link_to 'Edit', edit_admin_game_path(@admin_game) %> |
<%= link_to 'Back', admin_games_path %>