config/routes.rb
Rails.application.routes.draw do

  get 'about/about', as: 'about'

  get 'mboard/index'

  get 'mboard/new'

  get 'guestbooks/index'

  get 'admin/comments/index'

  devise_for :users, controllers: {

    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  mount Ckeditor::Engine => '/ckeditor'
  resources :posts do 
    resources :comments do
      resources :replies
    end
  end
  resources :category

  resources :games do 
    resources :comments
  end

  resources :mboards do
    resources :comments
  end

  namespace :admin do
    resources :posts do
      collection do
        delete 'multi_del'
      end
    end
    resources :comments do
      collection do
        delete 'multi_del'
      end
    end
    resources :replies do
      collection do
        delete 'multi_del'
      end
    end
    resources :games do
      collection do
        delete 'multi_del'
      end
    end
    resources :mboards do
      collection do
        delete 'multi_del'
      end
    end
  end

  get '/games/:id/new_review', to: 'games#add_review', as: 'new_review'
  
  get 'comments/:id/edit_review', to: "comments#edit_review", as: "edit_review"

  root 'posts#index'

  get '/category_post', to: 'posts#category_post'

  post '/mboards/add_comment', to: 'mboards#add_comment'

end

app/models/admin/reply.rb
class Admin::Reply < Reply
end

app/models/reply.rb
class Reply < ApplicationRecord
  belongs_to :comment
  validates :reply, presence: true
end

app/controllers/admin/replies_controller.rb
class Admin::RepliesController < ApplicationController
  layout "admin"
  before_action :set_admin_reply, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :auth_user

  # GET /admin/replies
  # GET /admin/replies.json
  def index
    @admin_replies = Admin::Reply.all
  end

  # GET /admin/replies/1
  # GET /admin/replies/1.json
  def show
  end

  # GET /admin/replies/new
  def new
    @admin_reply = Admin::Reply.new
  end

  # GET /admin/replies/1/edit
  def edit
  end

  # POST /admin/replies
  # POST /admin/replies.json
  def create
    @admin_reply = Admin::Reply.new(admin_reply_params)

    respond_to do |format|
      if @admin_reply.save
        format.html { redirect_to @admin_reply, notice: 'Reply was successfully created.' }
        format.json { render :show, status: :created, location: @admin_reply }
      else
        format.html { render :new }
        format.json { render json: @admin_reply.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/replies/1
  # PATCH/PUT /admin/replies/1.json
  def update
    respond_to do |format|
      if @admin_reply.update(admin_reply_params)
        format.html { redirect_to @admin_reply, notice: 'Reply was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_reply }
      else
        format.html { render :edit }
        format.json { render json: @admin_reply.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/replies/1
  # DELETE /admin/replies/1.json
  def destroy
    @admin_reply.destroy
    respond_to do |format|
      format.html { redirect_to admin_replies_url, notice: 'Reply was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def multi_del
    Reply.destroy_all(id: params[:del_replies])
    redirect_back(fallback_location: root_path, notice: '刪除成功') 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_reply
      @admin_reply = Admin::Reply.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_reply_params
      params.fetch(:admin_reply, {})
    end
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  before_action :set_reply, only: [:update, :destroy]
  before_action :authenticate_user!

  def create
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:comment_id])
    @reply = @comment.replies.build(reply_params)
    if @reply.save
      redirect_to post_url(@post)
    else
      redirect_to post_url(@post), alert: '回覆失敗'
    end
  end

  def update
    @reply = Reply.find(params[:id])
     @post = Post.find(params[:post_id])
    respond_to do |format|
      if @reply.update(reply_params)
        format.html { redirect_to @post, notice: '修改留言成功'}
        format.json { respond_with_bip(@reply) }
      end
    end
  end

  def destroy
    if @reply.destroy
      redirect_back fallback_location: root_path, notice: '刪除留言成功'
    end
  end

  private

  def reply_params
    params.require(:reply).permit(:name, :reply)
  end

  def set_reply
    @reply = Reply.find(params[:id])
  end

end

app/helpers/admin/replies_helper.rb
module Admin::RepliesHelper
  def find_blog(reply)
    comment = Comment.find(reply.comment_id)
    Post.find(comment.commentable_id)
  end
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/views/admin/replies/_form.html.erb
<%= form_tag multi_del_admin_replies_path, method: :delete do %>
  <div class="table-responsive"> 
    <table class="table">
      <thead>
        <tr>
          <th>選取</th>
          <th>留言人</th>
          <th>內容</th>
          <th>文章標題</th>
        </tr>
      </thead>

      <tbody>
        <% @admin_replies.each do |admin_reply| %>
          <tr>
            <td><%= check_box_tag "del_replies[]", admin_reply.id %></td>
            <td><%= admin_reply.name %></td>
            <td><%= admin_reply.reply %></td>
            <td><%= link_to find_blog(admin_reply).title, post_path(find_blog(admin_reply)) %></td>
            <td><%= link_to 'Destroy', admin_reply_path(admin_reply), method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <%= submit_tag "刪除所選留言", data: {contirm: '確定刪除?'}, class: 'btn btn-danger' %>
<% end %>

app/views/admin/replies/edit.html.erb
<h1>Editing Admin Reply</h1>

<%= render 'form', admin_reply: @admin_reply %>

<%= link_to 'Show', @admin_reply %> |
<%= link_to 'Back', admin_replies_path %>

app/views/admin/replies/index.html.erb
<h1>Blog留言管理</h1>
<div class="dropdown">
  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
    選擇管理區塊
    <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
    <li role="presentation"><%= link_to 'Blog回文管理', admin_comments_path(type: "blog"), role: 'menuitem', tabindex: '-1' %></li>
     <li role="presentation"><%= link_to 'Blog留言管理', admin_replies_path, role: 'menuitem', tabindex: '-1' %></li>
    <li role="presentation"><%= link_to '遊戲review留言管理', admin_comments_path(type: "game"), role: 'menuitem', tabindex: '-1' %></li>
     <li role="presentation"><%= link_to '留言板留言', admin_comments_path(type: "mboard"), role: 'menuitem', tabindex: '-1' %></li>
  </ul>
</div>
<br>

<%= render partial: 'form' %>

app/views/admin/replies/new.html.erb
<h1>New Admin Reply</h1>

<%= render 'form', admin_reply: @admin_reply %>

<%= link_to 'Back', admin_replies_path %>

app/views/admin/replies/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_admin_reply_path(@admin_reply) %> |
<%= link_to 'Back', admin_replies_path %>